name: CI

on:
  push:
    paths-ignore:
    - '**.rst'
    - '**.org'
    - '**.texi'
    - '**.info'
    - '**.md'
    - ChangeLog.*
    - NEWS
    branches-ignore:
    - master
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: paths
      run: |
        echo "$HOME/local/bin" >> $GITHUB_PATH
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig" >> $GITHUB_ENV
    - name: apt-get
      if: startsWith(runner.os, 'Linux')
      run: |
        sudo apt-get -yq update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gnutls-bin sharutils dirmngr libreadline-dev libcurl4-openssl-dev libxml2-dev libssl-dev libcairo2-dev libdbus-1-dev libfreetype6-dev libgif-dev libgio3.0-cil-dev libglib2.0-dev libgmp-dev libgnutls28-dev libharfbuzz-dev libjpeg-dev libjansson-dev liblcms2-dev libselinux1-dev libxml2-dev libpng-dev librsvg2-dev libtiff-dev libx11-dev libxext-dev libxpm-dev libgtk-3-dev zlib1g-dev libxaw7-dev
    - name: brew-haha
      if: startsWith(runner.os, 'macOS')
      run: |
        brew install libxml2 texinfo
        # github doc (unintelligible as of 20220428) suggests ">>" prepends to PATH.
        echo "`brew --prefix texinfo`/bin" >> $GITHUB_PATH
        echo "PKG_CONFIG_PATH=`brew --prefix libxml2`/lib/pkgconfig:$HOME/.local/lib/pkgconfig" >> $GITHUB_ENV
    - uses: actions/cache@v3
      id: cache-elisp-benchmarks
      with:
        path: elisp-benchmarks
        key: cache-elisp-benchmarks-000
    - uses: actions/checkout@v3
      if: steps.cache-elisp-benchmarks.outputs.cache-hit != 'true'
      with:
        repository: emacs-straight/elisp-benchmarks
        path: elisp-benchmarks
    - uses: actions/cache@v3
      id: cache-tree-sitter
      with:
        path: tree-sitter
        key: cache-tree-sitter-${{ runner.os }}-001
    - uses: actions/checkout@v3
      if: steps.cache-tree-sitter.outputs.cache-hit != 'true'
      with:
        repository: commercial-emacs/tree-sitter
        path: tree-sitter
        ref: 0.6.3alpha6
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: make-tree-sitter
      run: |
        mkdir -p $HOME/.local
        make -C tree-sitter install-ci
    - name: make-alt-xtoolkit
      if: matrix.os == 'ubuntu-20.04'
      run: |
        ./autogen.sh
        ./configure WERROR_CFLAGS='-Werror' --prefix=$HOME/.local --with-x-toolkit=lucid --without-cairo --without-xaw3d --without-gconf --without-libsystemd
        make -j4 -C src
    - name: make-linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        ./autogen.sh
        ./configure WERROR_CFLAGS='-Werror' --prefix=$HOME/.local --with-tree-sitter
        make -j4 check
    - name: make-macos
      if: startsWith(runner.os, 'macOS')
      run: |
        ./autogen.sh
        ./configure --prefix=$HOME/.local
        make -j4 check
    - name: elisp-benchmarks
      if: matrix.os == 'ubuntu-latest'
      run: |
        src/emacs -batch -l ./elisp-benchmarks/elisp-benchmarks.el --eval "(custom-set-variables (quote (elb-runs 1)))" -f elisp-benchmarks-run
