name: CI

on:
  push:
    paths-ignore:
    - '**.rst'
    - '**.org'
    - '**.texi'
    - '**.info'
    - '**.md'
    - ChangeLog.*
    - NEWS
    branches-ignore:
    - master
    - main

jobs:
  build-w32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache-tree-sitter
      with:
        path: tree-sitter
        key: cache-tree-sitter-${{ runner.os }}-000
    - uses: actions/checkout@v3
      if: steps.cache-tree-sitter.outputs.cache-hit != 'true'
      with:
        repository: commercial-emacs/tree-sitter
        path: tree-sitter
        ref: 0.6.3alpha6
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: make
      run: |
        ./autogen.sh
        ./configure --prefix=$HOME/.local
        make -j4 -C src
