name: CI

on:
  push:
    paths-ignore:
    - '**.rst'
    - '**.org'
    - '**.texi'
    - '**.info'
    - '**.md'
    - ChangeLog.*
    - NEWS
    branches-ignore:
    - master
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
    steps:
    - run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v3
    - name: paths
      run: |
        echo "$HOME/local/bin" >> $GITHUB_PATH
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig" >> $GITHUB_ENV
    - name: brew-haha
      if: startsWith(runner.os, 'macOS')
      run: |
        brew install libxml2 texinfo
        # github doc (unintelligible as of 20220428) suggests ">>" prepends to PATH.
        echo "`brew --prefix texinfo`/bin" >> $GITHUB_PATH
        echo "PKG_CONFIG_PATH=`brew --prefix libxml2`/lib/pkgconfig:$HOME/.local/lib/pkgconfig" >> $GITHUB_ENV
    - uses: actions/cache@v3
      id: cache-tree-sitter
      with:
        path: tree-sitter
        key: cache-tree-sitter-${{ runner.os }}-001
    - uses: actions/cache@v3
      id: cache-tree-sitter-cli
      with:
        path: $HOME/.cargo/bin
        key: cache-tree-sitter-cli-${{ runner.os }}-000
    - uses: actions/checkout@v3
      if: steps.cache-tree-sitter.outputs.cache-hit != 'true'
      with:
        repository: commercial-emacs/tree-sitter
        path: tree-sitter
        ref: v0.20.8alpha1
    - uses: actions/checkout@v3
      with:
        repository: tree-sitter/tree-sitter-c
        path: tree-sitter-c
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: make-tree-sitter
      if: steps.cache-tree-sitter-cli.outputs.cache-hit != 'true'
      run: |
        mkdir -p $HOME/.local
        make -C tree-sitter install-cli
    - name: make-tree-sitter-c
      run: |
        echo "dumplibpath=$($HOME/.cargo/bin/tree-sitter dump-libpath)" >> $GITHUB_ENV
        (cd tree-sitter-c ; $HOME/.cargo/bin/tree-sitter generate ; $HOME/.cargo/bin/tree-sitter test )
    - uses: actions/upload-artifact@v3
      with:
        name: mz.artifact
        path: ${{ env.dumplibpath }}/c.dylib
